#version 430 core
layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D states;

uniform float u_time;

void set(ivec2 pixel_coords, vec4 state) {
	imageStore(states, pixel_coords, state);
}

void main() {
	ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
	ivec2 dims = imageSize(states);

	vec2 uv = (vec2(pixel_coords) / vec2(dims) - .5) * 2;
	uv.x *= float(dims.x) / float(dims.y);

	set(pixel_coords, vec4(uv, 0, 0));
}