#version 430 core
layout(local_size_x = 8, local_size_y = 4, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D u_screen;

uniform float u_time;

void main() {
	ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
	ivec2 dims = imageSize(u_screen);

	vec2 uv = (vec2(pixel_coords) / vec2(dims) - .5) * 2;
	uv.x *= float(dims.x) / float(dims.y);

	vec2 O = vec2(sin(u_time), 0);

	vec4 col_new = vec4(length(uv - O) < .4 ? vec3(1) : vec3(0), 1);

	vec4 col_prev = imageLoad(u_screen, pixel_coords);
	vec4 col_result = mix(col_prev, col_new, .1);
	imageStore(u_screen, pixel_coords, col_result);
}